### ISSUE TITLE
Seems to be broken under node 0.12.0

### ISSUE THREAD

**Issue by adius** [inexorabletash/text-encoding#29]
Since the upgrade it gets stuck in an endless loop.

**Comment by inexorabletash** [comment]
Do you have a repro?

**Comment by inexorabletash** [comment]
With 0.12.0 this works for me:

```js
var e = require('text-encoding');
var enc = new e.TextEncoder().encode('hello world');
var dec = new e.TextDecoder().decode(enc);
console.log(dec);
```

Can you give an example that's failing?

**Comment by adius** [comment]
I think this issue can be closed.
I probably used accidentally io.js instead of node.js at that time and
I guess that's not a thing anymore =P

**Comment by danieltigse** [comment]
How do I use it with node? I have this error:
```
TypeError: Called as a function. Did you forget 'new'?
```
I am using the code above
