### ISSUE TITLE
Encoding failing with windows-1254

### ISSUE THREAD

**Issue by E-Mud** [inexorabletash/text-encoding#32]
I found a problem when trying to encode a string with turkish characters in windows 1254:

    TypeError: Cannot read property 'indexOf' of undefined
         at indexPointerFor (encoding.js:823)
         at SingleByteEncoder.handler (encoding.js:1434)
         at Object.encode (encoding.js:1122)

Way to reproduce:

    var textEncoder = new CustomTextEncoder('windows-1254', {NONSTANDARD_allowLegacyEncoding: true}),
        contentEncoded = textEncoder.encode(["Tuğce"]);

**Comment by inexorabletash** [comment]
Hrm, works for me:

```js
new TextEncoder('windows-1254', {NONSTANDARD_allowLegacyEncoding: true}).encode('Tuğce')
// [84, 117, 240, 99, 101]
```

(Note: you don't want `[]` around the input to `encode()`, otherwise you're relying implicitly on the behavior of Array's toString(), but it's not the cause of your problem here.)

**Comment by inexorabletash** [comment]
This would occur if `encoding-indexes` were defined in the global state, but `"windows-1254"` were not present as a key. Can you check that the copy of `lib/encoding-indexes.js` you're using is not truncated?

**Comment by E-Mud** [comment]
Sorry for the delay.

I checked and we only had windows-1252 in indexes. Apparently it was truncated because is the encoding we were using before, and there was no need to have the complete structure.

Since this is not a problem in text-encoding I guess the most logical thing is to close this issue.
