### ISSUE TITLE
What is the copyright from test/testharness*.js ?

### ISSUE THREAD

**Issue by SnarkBoojum** [inexorabletash/text-encoding#37]
I know the license is the BSD-3-clause one, but what worth is a license mentioning the copyright holders if they're not made explicit?

I can't help but notice that testharness.js looks like a mix of the W3C version and it's api -- so perhaps a copyright to the W3C is correct?

**Comment by inexorabletash** [comment]
Yeah, I tossed that in in a hurry. Can't believe I left it that way.

I'll CC0 the whole thing where not covered elsewhere (testharness and the indexes)

**Comment by inexorabletash** [comment]
Okay, testharness.js is now a submodule, which includes its own LICENSE.

c9bf7e5860d3ec2fcd29ceb21e451d55ebf19c64
