### ISSUE TITLE
Proposal: use native string_decoder for popular encodings

### ISSUE THREAD

**Issue by RReverser** [inexorabletash/text-encoding#41]
Using `https://nodejs.org/api/string_decoder.html` should theoretically significantly decrease size of manually supported code as it already provides proper decoding algorithms for popular (supported in Node) encodings.

**Comment by inexorabletash** [comment]
This polyfill is aimed at browser usage. Node support is secondary at best.

**Comment by RReverser** [comment]
Oh I see. Do you possibly know a good polyfill for Node then? Latest Chrome and FF already have TextEncoder, but really missing such wrapper in Node.js for consistency.
