### ISSUE TITLE
Publish ES6 modules

### ISSUE THREAD

**Issue by arv** [inexorabletash/text-encoding#42]
A lot of tool chains are moving towards using ES6 modules (rollup for example) and having ES6 modules published to npm would make this package easier to consume.

**Comment by tracker1** [comment]
@arv doesn't need to be an ES6 module as published in NPM, babel and most other loaders will convert import/export to be commonjs compatible...  In this case, just needed to setup appropriate exports.

**Comment by arv** [comment]
@tracker1. See OP. Rollupjs can convert cjs to es modules but the current format is not compatible with their plugin. Things would be better going guests if the source was in es modules and converted to cjs.
