### ISSUE TITLE
Divide into Encode/Decode

### ISSUE THREAD

**Issue by tererecool** [inexorabletash/text-encoding#48]
It would be nice to be able to only have the Encode or Decode code, the code is really long and for my actual project that must be as small as possible I am needing only the Encode part, is this possible to do?

**Comment by inexorabletash** [comment]
If you only need to encode utf-8 and don't need the whole API there are much more succinct ways of doing it, such as http://ecmanaut.blogspot.com/2006/07/encoding-decoding-utf8-in-javascript.html
