### ISSUE TITLE
Decode to =?GB18030?B?lDnaMw==?=: failed

### ISSUE THREAD

**Issue by lygstate** [inexorabletash/text-encoding#49]
The following GB18030 decode incorrect.
`
=?GB18030?B?lDnaMw==?=:
`

**Comment by inexorabletash** [comment]
Can you provide the error as a code sample?

**Comment by inexorabletash** [comment]
No feedback, closing.

**Comment by Artoria2e5** [comment]
This is an [RFC 2047](https://tools.ietf.org/html/rfc2047) "encoded-word", written in the "B" (base64) encoding. So it's basically:

```JS
new TextDecoder('gb18030').decode(
    Uint8Array.from(
        atob('lDnaMw=='), 
        (ch) => (ch.codePointAt(0))))
// "💩"
```

**Comment by inexorabletash** [comment]
Thanks for providing the repro!
