### ISSUE TITLE
Undocumented breaking changes introduced somewhere between 0.5.2 and 0.5.5

### ISSUE THREAD

**Issue by cgwyllie** [inexorabletash/text-encoding#51]
Hi, 

We depended on ^0.5.2, and our CI server just installed 0.5.5, which broke the build. We received an exception thrown from here https://github.com/inexorabletash/text-encoding/blob/master/lib/encoding.js#L979.

The solution is simple enough (a change from `TextDecoder('utf-8').decode(...)` to creating an instance of `var decoder = new TextDecoder('utf-8'); decoder.decode(...)`), but it caused us some debug time to fix because the documentation isn't up to date, and the breaking change was introduced in a patch release.

Was this intentional, or are the documentation updates just pending?

Thanks!

**Comment by inexorabletash** [comment]
You can write `new TextDecoder('utf-8').decode(...)` - the change is that `new` is now required. Previously the nonstandard Gecko behavior of allowing construction of host objects w/o `new` operator was followed, but Gecko fixed that so there was no reason to maintain that.

Docs _were_ updated in 825cdab34529faf7933bad6697fadc83c95a4838 - deleting the bit about supporting nonstandard behavior.

My apologies - I should have bumped the minor version then, it didn't occur to me.

**Comment by cgwyllie** [comment]
Hey, thanks for the prompt reply. Totally fair enough on the change, it makes total sense.

Oops, my bad on the documentation front. It seems I had just skipped to the code samples, none of which show the correct usage with the `new` operator.

I'm struggling to see the updated documentation on Github, although I can see it in the documentation.

I'll put in a PR to update all code examples if that would be ok.

**Comment by inexorabletash** [comment]
Ugh, I saw your message that I'd missed updating the examples in README but didn't notice you'd made it a PR so I updated the README myself. :(

Thanks for pointing out the problem!

**Comment by cgwyllie** [comment]
Ah, sorry! Feel free to close the PR, sorry about the double work :-\
