### ISSUE TITLE
stringencoding vs text-encoding

### ISSUE THREAD

**Issue by barrydegraaff** [inexorabletash/text-encoding#54]
I am using stringencoding in one of my projects... but it feels pretty dead to me
https://www.npmjs.com/package/stringencoding
https://github.com/defunctzombie/stringencoding

Is seems text-encoding is an updated fork, can someone explain the relation between stringencoding and text-encoding, what is the functional difference.

**Comment by inexorabletash** [comment]
@defunctzombie's repo a fork of this, back from when this was hosted at  https://code.google.com/p/stringencoding/. I don't know anything about that npm package.

**Comment by defunctzombie** [comment]
That package is the package I published (back when I had a different npm username) which is indeed a publish of the stringencoding package when it was hosted at google code. Does that package need to be deprecated now?

**Comment by inexorabletash** [comment]
Thanks for jumping in, @defunctzombie ! That's a good question.

My goal with this repo is a polyfill of the [web standard](https://encoding.spec.whatwg.org), which means it tracks the standard and browser implementations. For example, you can't use any encoder but utf-8, and the set of decodings has become more limited over time. There's an escape hatch to use other encoders (pass  `{ NONSTANDARD_allowLegacyEncoding: true }` to the ctor) but that's probably unexpected to developers not approaching this as a polyfill (i.e. most node users?)

There have certainly been many important fixes, though. So deprecation - but certainly not outright removal - is probably the right thing to do.

I welcome more discussion, though. And I'm not a node user, so scoped changes that make things more appealing to node users are welcome; maybe we can flip the nonstandard flag on automagically if loaded as a node module or something.

(I do need to publish an updated version of this to npm though. I wanted to roll in some other minor changes from the standard first but I've been busy with other projects.)

**Comment by barrydegraaff** [comment]
Thanks for this info, it seems inexorabletash/text-encoding is the most active of a lot of forks, I will see if https://github.com/emailjs/emailjs-addressparser is compatible with  inexorabletash/text-encoding. And if not file a bug there.

**Comment by inexorabletash** [comment]
Closing this - nothing actionable in this repo.
