### ISSUE TITLE
Failed to detect native methods in TypeScript

### ISSUE THREAD

**Issue by mlocati** [inexorabletash/text-encoding#73]
I'm using your library on a TypeScript project.
In my `package.json` file I have these dependencies:
```
"@types/text-encoding": "0.0.30"
"text-encoding": "^0.6.4"
```

In my TypeScript code I have:

```TypeScript
import * as encoding from 'text-encoding';
let encoder = new encoding.TextEncoder();
let bytes = encoder.encode(string);
```

Everything is working great, but this library fails to detect the native libraries: debugging the code, I've seen that in [these lines](https://github.com/inexorabletash/text-encoding/blob/v0.6.4/lib/encoding.js#L3298-L3301) `global` evaluates to `Object {encoding-indexes: Object}` instead of `window`.

In my project I introduced a workaround ([I detect the native functions](https://github.com/mlocati/jsgettext/blob/ba35c1044aabd3980fb6ccc26c4cc8a55aac7480/src/Gettext/Charset.ts#L12-L17) and [use them](https://github.com/mlocati/jsgettext/blob/ba35c1044aabd3980fb6ccc26c4cc8a55aac7480/src/Gettext/Charset.ts#L26-L33)), but it would be nice to have this issue fixed in your (great) library...

**Comment by Ruffio** [comment]
@inexorabletash should it be switched to window instead of global?

**Comment by inexorabletash** [comment]
@Ruffio that would probably break node and definitely break non-module use in workers (i.e. plain `importScripts`

Overall, the library needs to be updated to be friendly with node modules, ES6 modules, whatever TypeScript is using, and (the only one I actually care about) direct inclusion as scripts in HTML and Worker contexts.

I'm not planning to spend any time on an overhaul; it's just not a priority for me. So comprehensive, broadly tested PRs are welcome.

**Comment by NanYoMy** [comment]
god damn!
import * as encoding from 'text-encoding';
let encoder = new encoding.TextEncoder();
let bytes = encoder.encode(string);
it works!!!!!!!
i had use this code, but it will cause some type error.
import TextEncoder from 'text-encoding';
let encoder=new TextEncoder();

**Comment by inexorabletash** [comment]
Sounds like you solved the problem with your first example?
