### ISSUE TITLE
Encode Chinese Problem

### ISSUE THREAD

**Issue by Nitromethane** [inexorabletash/text-encoding#74]
```
<script type="text/javascript">
        var csvContent = 'éà; ça; 12\nà@€; çï; 13中文',
            textEncoder = new CustomTextEncoder('windows-1252', {NONSTANDARD_allowLegacyEncoding: true}),
            fileName = 'some-data.csv';

        var a = document.getElementById('download-csv');
        a.addEventListener('click', function(e) {
            var csvContentEncoded = textEncoder.encode([csvContent]);
            var blob = new Blob([csvContentEncoded], {type: 'text/csv;charset=windows-1252;'});
            saveAs(blob, fileName);
            e.preventDefault();
        });
</script>
```
this will cause a problem;

> encoding.js:273 Uncaught TypeError: The code point 20013 could not be encoded.
    at encoderError (encoding.js:273)
    at SingleByteEncoder.handler (encoding.js:1438)
    at TextEncoder.encode (encoding.js:1122)
    at HTMLAnchorElement.<anonymous> (example.html:21)

**Comment by inexorabletash** [comment]
The windows-1252 encoding only handles Western European scripts. The characters 中文 can't be encoded in windows-1252, hence the error. 

What behavior are you expecting?

**Comment by Ruffio** [comment]
@Nitromethane do you have an answer to the question?

**Comment by inexorabletash** [comment]
I think there was just an understanding of how character encodings work. Closing, pending further data.
