### ISSUE TITLE
'\n' encoded as 10 13

### ISSUE THREAD

**Issue by Singein** [inexorabletash/text-encoding#80]

**Comment by inexorabletash** [comment]
Can you provide more details? What are you trying, what is the output you are seeing, and how does it differ from what you expect?

**Comment by Fuermohao** [comment]
![issue__](https://user-images.githubusercontent.com/18239246/44642320-3faeae80-a9fe-11e8-899a-ba3f5cf637c3.png)
this is the uint8array returned by FileReader.

the string is "aabbccdd\naabbccdd"

**Comment by Fuermohao** [comment]
![issue_encoding](https://user-images.githubusercontent.com/18239246/44642380-7edcff80-a9fe-11e8-9020-a19d19073a85.png)
this is uint8array is returned by your TextEncoder
thanks for help..

**Comment by inexorabletash** [comment]
Please provide a code sample. Also, compare against the `TextEncoder` implemented natively in Chrome or Firefox.

Polyfill: 

```
new TextEncoder().encode('abc\ndef')
> Uint8Array(7) [97, 98, 99, 10, 100, 101, 102]
```

Chrome:
```
new TextEncoder().encode('abc\ndef')
> Uint8Array(7) [97, 98, 99, 10, 100, 101, 102]
```

Firefox:
```
new TextEncoder().encode('abc\ndef')
> Uint8Array(7) [97, 98, 99, 10, 100, 101, 102]
```

**Comment by Fuermohao** [comment]
em, I am so sorrry to bother you. it's my editor's EOL mode...cause this problem...
thanks for your replying!
